version: "3"


services:
  hirkano_postgresql:
    image:
      postgres:14
    container_name: hirkano_postgresql
    volumes:
      - hirkano_postgresql_volume:/var/lib/postgresql/data
    restart: always
    env_file: configs/.env.d/.env
    networks:
      - hirkano_network
  
  hirkano:
    build: 
      context: .
      dockerfile: docker.conf.d/hirkano/Dockerfile
    container_name: hirkano
    volumes:
      - hirkano_static_volume:/opt/hirkano/hirkano/static
      - hirkano_media_volume:/opt/hirkano/hirkano/media
    restart: always
    ports:
      - "8010:8010"
    networks:
      - hirkano_network
    expose:
      - 8010


volumes:
  hirkano_static_volume:
    external:
      true
  hirkano_media_volume:
    external:
      true
  hirkano_postgresql_volume:
    external:
        true


networks:
  hirkano_network:     
    external: 
      true