# Generated by Django 4.1.3 on 2022-12-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_activity_blog_contant_us_message_person_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Projects',
        ),
    ]
