# Generated by Django 4.1.3 on 2022-12-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_activity_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Social_Id',
        ),
        migrations.AddField(
            model_name='person',
            name='FaceBook_Id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Gmail_Id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Instagram_Id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Twiter_Id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
