# Generated by Django 4.1.3 on 2022-12-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_person_social_id_person_facebook_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='FaceBook_Id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='Gmail_Id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='Instagram_Id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='Twiter_Id',
            field=models.CharField(max_length=256),
        ),
    ]
