# Generated by Django 4.1.3 on 2022-12-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_person_facebook_id_alter_person_gmail_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide_show/images/')),
                ('text', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
            ],
        ),
    ]
