# Generated by Django 4.1.3 on 2022-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_person_facebook_id_alter_person_gmail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
