# Generated by Django 4.1.3 on 2022-12-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_happy_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Happy_Client',
            new_name='HappyClient',
        ),
        migrations.DeleteModel(
            name='Contant_Us',
        ),
    ]
