# Generated by Django 4.1.3 on 2022-12-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='time',
        ),
    ]
